// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using exempleApiMessagerie.Models;

#nullable disable

namespace exempleApiMessagerie.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("exempleApiMessagerie.Models.Messages.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("EnvoyeurId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ReceveurId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(65535)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvoyeurId");

                    b.HasIndex("ReceveurId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("exempleApiMessagerie.Models.Utilisateurs.Utilisateur", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("exempleApiMessagerie.Models.Messages.Message", b =>
                {
                    b.HasOne("exempleApiMessagerie.Models.Utilisateurs.Utilisateur", "Envoyeur")
                        .WithMany("MessagesEnvoyes")
                        .HasForeignKey("EnvoyeurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exempleApiMessagerie.Models.Utilisateurs.Utilisateur", "Receveur")
                        .WithMany("MessagesRecus")
                        .HasForeignKey("ReceveurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Envoyeur");

                    b.Navigation("Receveur");
                });

            modelBuilder.Entity("exempleApiMessagerie.Models.Utilisateurs.Utilisateur", b =>
                {
                    b.Navigation("MessagesEnvoyes");

                    b.Navigation("MessagesRecus");
                });
#pragma warning restore 612, 618
        }
    }
}
